import React from 'react';
import styled from 'styled-components';
import { FiImage, FiVideo, FiMic, FiDownload } from 'react-icons/fi';

const GalleryContainer = styled.div`
  background: white;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.05);
`;

const GalleryHeader = styled.h3`
  font-size: 1rem;
  color: #495057;
  margin-bottom: 15px;
  display: flex;
  align-items: center;
  gap: 8px;
`;

const AssetGrid = styled.div`
  display: grid;
  grid-template-columns: 1fr;
  gap: 12px;
`;

const AssetCard = styled.div`
  border: 1px solid #e9ecef;
  border-radius: 8px;
  overflow: hidden;
  background: #fff;
`;

const AssetHeader = styled.div`
  padding: 12px;
  background: #f8f9fa;
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const AssetTitle = styled.div`
  font-weight: 500;
  color: #212529;
  font-size: 0.9rem;
`;

const AssetType = styled.div`
  font-size: 0.75rem;
  padding: 2px 8px;
  border-radius: 12px;
  background: ${props => {
    if (props.type === 'diagram') return '#d1ecf1';
    if (props.type === 'video') return '#f8d7da';
    if (props.type === 'audio') return '#d4edda';
    return '#d1ecf1';
  }};
  color: ${props => {
    if (props.type === 'diagram') return '#0c5460';
    if (props.type === 'video') return '#721c24';
    if (props.type === 'audio') return '#155724';
    return '#0c5460';
  }};
`;

const AssetBody = styled.div`
  padding: 12px;
`;

const AssetInfo = styled.div`
  font-size: 0.8rem;
  color: #6c757d;
  margin-bottom: 8px;
`;

const AssetActions = styled.div`
  display: flex;
  gap: 8px;
`;

const ActionButton = styled.button`
  padding: 4px 8px;
  border-radius: 6px;
  background: #e9ecef;
  border: none;
  font-size: 0.8rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 4px;
  
  &:hover {
    background: #dee2e6;
  }
`;

const MediaGallery = () => {
  const assets = [
    {
      id: 'img_1',
      type: 'diagram',
      title: 'AI Concept Map',
      url: '/api/assets/diagram_1.png',
      generated_by: 'VisualAgent',
      timestamp: '2023-10-26T08:56:00Z'
    },
    {
      id: 'video_1',
      type: 'video',
      title: 'Introduction to Neural Networks',
      url: '/api/assets/video_1.mp4',
      duration: '5:30',
      generated_by: 'MultimediaAgent',
      timestamp: '2023-10-26T09:49:00Z'
    },
    {
      id: 'audio_1',
      type: 'audio',
      title: 'AI Explained',
      url: '/api/assets/audio_1.mp3',
      duration: '8:15',
      generated_by: 'MultimediaAgent',
      timestamp: '2023-10-26T09:41:00Z'
    }
  ];

  const getIcon = (type) => {
    switch (type) {
      case 'diagram': return <FiImage />;
      case 'video': return <FiVideo />;
      case 'audio': return <FiMic />;
      default: return <FiImage />;
    }
  };

  return (
    <GalleryContainer>
      <GalleryHeader><FiImage /> Generated Media Gallery</GalleryHeader>
      <AssetGrid>
        {assets.map(asset => (
          <AssetCard key={asset.id}>
            <AssetHeader>
              <AssetTitle>{asset.title}</AssetTitle>
              <AssetType type={asset.type}>
                {asset.type}
              </AssetType>
            </AssetHeader>
            <AssetBody>
              <AssetInfo>
                Generated by {asset.generated_by} • {new Date(asset.timestamp).toLocaleString()}
                {asset.duration && ` • Duration: ${asset.duration}`}
              </AssetInfo>
              <AssetActions>
                <ActionButton><FiDownload /> Download</ActionButton>
              </AssetActions>
            </AssetBody>
          </AssetCard>
        ))}
      </AssetGrid>
    </GalleryContainer>
  );
};

export default MediaGallery;